#!/usr/bin/env python3
"""
Auto-generated CLI wrapper for magick.exe
Generated by CLI-Anything
"""

import argparse
import json
import subprocess
import sys
import os

SOFTWARE_PATH = r"C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe"

def run(args):
    """Run the wrapped software with given arguments."""
    cmd = [SOFTWARE_PATH] + args
    result = subprocess.run(cmd, capture_output=True, text=True)
    return {
        "stdout": result.stdout,
        "stderr": result.stderr,
        "returncode": result.returncode
    }

def main():
    parser = argparse.ArgumentParser(description="CLI wrapper for magick.exe")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--version", action="store_true", help="Show version")
    parser.add_argument("args", nargs="*", help="Arguments to pass to magick.exe")
    
    args = parser.parse_args()
    
    if args.version:
        print("CLI-Anything wrapper for magick.exe")
        return
    
    result = run(args.args)
    
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(result["stdout"], end="")
        if result["stderr"]:
            print(result["stderr"], file=sys.stderr, end="")
        sys.exit(result["returncode"])

if __name__ == "__main__":
    main()
